/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.soundquiz.client.view;

import com.google.gson.JsonArray;
import com.google.gson.JsonParser;
import com.mycompany.soundquiz.client.connection.ClientConnection;
import com.mycompany.soundquiz.client.connection.ClientNetwork;
import com.mycompany.soundquiz.client.connection.MessageRouter;
import java.io.*;
import java.net.*;
import javax.swing.JOptionPane;
import com.mycompany.soundquiz.client.utils.Config;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
/**
 *
 * @author Admin
 */
public class MainFrm extends javax.swing.JFrame {

    /**
     * Creates new form MainFrm
     */
    public MainFrm() {
        initComponents();
        setLocationRelativeTo(null);
        
      
        try {
            client = ClientConnection.getInstance();
            connectServerViaNgrok();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        txtPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnConnectServer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kết nối tới Server");

        jLabel2.setText("IP");

        jLabel3.setText("Port");

        btnConnectServer.setText("Kết nối");
        btnConnectServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectServerActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtIP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPort, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnConnectServer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConnectServer)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPort)
                                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 108, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConnectServer)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnConnectServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectServerActionPerformed
        String ip = txtIP.getText();
        if (!validIpAddress(ip)) {
            JOptionPane.showMessageDialog(this, "Địa chỉ Ip không hợp lệ", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Integer port;
        try {
            port = Integer.parseInt(txtPort.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Port phải là số nguyên!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return;
        }

        connectServer(ip, port);
    }//GEN-LAST:event_btnConnectServerActionPerformed

    private static String getLatestNgrokUrl() throws Exception {
        System.out.println("getLatestNgrokUrl");
        OkHttpClient client = new OkHttpClient();
        String url = Config.get("supabase.url") + "/rest/v1/ngrok_url?order=created_at.desc&limit=1";
//        JOptionPane.showMessageDialog(null, url, "Debug", JOptionPane.INFORMATION_MESSAGE);
        String apikey = Config.get("supabase.apikey");
        
        System.out.println(url + " - " + apikey);

        Request request = new Request.Builder()
                .url(url)
                .get()
                .addHeader("apikey", apikey)
                .addHeader("Authorization", "Bearer " + apikey)
                .build();

        try (Response response = client.newCall(request).execute()) {
            if (!response.isSuccessful()) {
                throw new RuntimeException("Get ngrokurl failed: " + response);
            }

            String json = response.body().string();  
            System.out.println(json);              

            JsonArray arr = JsonParser.parseString(json).getAsJsonArray();
            if (arr.size() == 0) {
                return null;
            }
            return arr.get(0).getAsJsonObject().get("url").getAsString();
        }
    }

    
    private void connectServer(String ip, Integer port) {
        System.out.println("Try to connect to server");

        try {
            client.connect(ip, port);            
//            client.connectViaNgrok(getLatestNgrokUrl());
            this.setVisible(false);

            java.awt.EventQueue.invokeLater(() -> {
                new LoginFrm().setVisible(true);
            });
            
            
        } catch (UnknownHostException e1) {
            JOptionPane.showMessageDialog(this,
                    "Không tìm thấy host: " + ip,
                    "Lỗi kết nối",
                    JOptionPane.ERROR_MESSAGE);

        } catch (ConnectException e2) {
            JOptionPane.showMessageDialog(this,
                    "Không thể kết nối tới server (có thể server chưa chạy).",
                    "Lỗi kết nối",
                    JOptionPane.ERROR_MESSAGE);

        } 
        catch (Exception e3) {
            JOptionPane.showMessageDialog(this,
                    "Lỗi khi kết nối: " + e3.getMessage(),
                    "Lỗi kết nối",
                    JOptionPane.ERROR_MESSAGE);

        }

    }
    
    private void connectServerViaNgrok1() {
        System.out.println("Try to connect to server");

        new Thread(() -> {
            try {
                String url = getLatestNgrokUrl();
                System.out.println("URL = " + url);
                client.connectViaNgrok(url);

                java.awt.EventQueue.invokeLater(() -> {
                    this.dispose();
                    new LoginFrm().setVisible(true);
                });
            } catch (Exception e3) {
                e3.printStackTrace();
            }
        }).start();

    }
private void connectServerViaNgrok() {
    // DEBUG: Hiện dialog ngay khi vào hàm
//    JOptionPane.showMessageDialog(this, "Kết nối tới Server qua Ngrok tunnel!", "Debug", JOptionPane.INFORMATION_MESSAGE);
    
    System.out.println("Try to connect to server via ngrok");

    new Thread(() -> {
        try {
            // DEBUG: Hiện dialog khi bắt đầu get URL
//            java.awt.EventQueue.invokeLater(() -> {
//                JOptionPane.showMessageDialog(this, "Đang lấy URL ngrok...", "Debug", JOptionPane.INFORMATION_MESSAGE);
//            });
            
            String url = getLatestNgrokUrl();
            System.out.println("URL = " + url);
            
            // DEBUG: Hiện URL đã lấy được
//            java.awt.EventQueue.invokeLater(() -> {
//                JOptionPane.showMessageDialog(this, "URL lấy được: " + url, "Debug", JOptionPane.INFORMATION_MESSAGE);
//            });
            
            client.connectViaNgrok(url);

            java.awt.EventQueue.invokeLater(() -> {
//                JOptionPane.showMessageDialog(this, "Kết nối thành công!", "Debug", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                new LoginFrm().setVisible(true);
            });
            
        } catch (Exception e3) {
            e3.printStackTrace();
            // DEBUG: Hiện lỗi chi tiết
            java.awt.EventQueue.invokeLater(() -> {
                JOptionPane.showMessageDialog(this, 
                    "LỖI: " + e3.getClass().getSimpleName() + "\n" + e3.getMessage(), 
                    "Debug Error", 
                    JOptionPane.ERROR_MESSAGE);
            });
        }
    }).start();
}
    public boolean validIpAddress(String ipAddress) {
        String[] numbers = ipAddress.split("\\.");
        if (numbers.length != 4) {
            return false;
        }

        for (String str : numbers) {
            try {
                int i = Integer.parseInt(str);
                if ((i < 0) || (i > 255)) {
                    return false;
                }
            } catch (NumberFormatException e) {
                return false;
            }
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrm().setVisible(true);
            }
        });
    }

    private ClientConnection client;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnectServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
