/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.soundquiz.client.view;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.reflect.TypeToken;
import com.mycompany.soundquiz.client.connection.ClientConnection;
import com.mycompany.soundquiz.client.connection.ClientNetwork;
import com.mycompany.soundquiz.client.connection.MessageRouter;
import com.mycompany.soundquiz.client.dto.MessageRequest;
import com.mycompany.soundquiz.client.dto.MessageResponse;
import com.mycompany.soundquiz.client.model.Music;
import com.mycompany.soundquiz.client.model.Question;
import java.io.ByteArrayInputStream;
import java.util.List;
import java.util.UUID;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.util.Base64;
import java.util.Timer;
import java.util.TimerTask;


/**
 *
 * @author Admin
 */
public class PlayGameFrm extends javax.swing.JFrame {
    private ClientNetwork clientNetwork;
    private List<Music> songs;
    private Question question;
    private int roomId;
    private int currentQuestionIndex;
    private int myScore;
    private Timer gameTimer;
    private Clip currentClip;

    /**
     * Constructor mới cho game flow
     */
    public PlayGameFrm(String listSongJson, String questionJson, int roomId) {
        this.roomId = roomId;
        this.currentQuestionIndex = 0;
        this.myScore = 0;
        this.gameTimer = new Timer();

        initComponents();
        setLocationRelativeTo(null);

        try {
            clientNetwork = ClientNetwork.getInstance();
        } catch (Exception e) {
            e.printStackTrace();
        }

        // Parse songs and question
        Gson gson = new Gson();
        java.lang.reflect.Type listType = new TypeToken<List<Music>>() {}.getType();
        this.songs = gson.fromJson(listSongJson, listType);
        this.question = gson.fromJson(questionJson, Question.class);

        // Setup UI with question
        setupQuestionUI();
        disableAnswers();

        // Register broadcast for final scores
        MessageRouter.getInstance().registerBroadcastHandler("final_scores", response -> {
            SwingUtilities.invokeLater(() -> handleFinalScores(response.getMessage()));
        });

        // Start game
        startNextQuestion();
    }

    /**
     * Constructor cũ (deprecated)
     */
    public PlayGameFrm(List<Music> listMusic) {
        initComponents();
        setLocationRelativeTo(null);
        
        try {
            clientNetwork = ClientNetwork.getInstance();
        } catch (Exception e) {
        }
        
        Music music = listMusic.get(0);
        img.setContentType("text/html");
        img.setText("<html>"
                + "<img src='" + music.getImage() + "' width='200'>"
                + "</html>");
        img.setEditable(false);
        img.setOpaque(false);
        img.setBorder(null);
        img.setHighlighter(null);

        img.setCaret(null);
        
        MessageRequest request = new MessageRequest();
        request.setType("getSegment");
        request.setContent("{\"songFile\":\"" + music.getFileName() + "\",\"segmentSeconds\":10}");
        String reqId = UUID.randomUUID().toString();
        request.setId(reqId); 
        
        
        MessageRouter.getInstance().registerRequestHandler(reqId, response -> {
            SwingUtilities.invokeLater(() -> {
                
                if (MessageResponse.SUCCESS.equals(response.getStatus())) {
                    String base64Data = response.getMessage();
                    byte[] audioBytes = Base64.getDecoder().decode(base64Data);

                    try (ByteArrayInputStream bais = new ByteArrayInputStream(audioBytes); 
                            AudioInputStream audioStream = AudioSystem.getAudioInputStream(bais)) {

                        Clip clip = AudioSystem.getClip();
                        clip.open(audioStream);
                        clip.start();

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
                MessageRouter.getInstance().unregisterRequestHandler(reqId);
            });
        });

        // Gửi request
        clientNetwork.sendMessage(request);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        img = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));

        jPanel2.setBackground(new java.awt.Color(251, 251, 251));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jRadioButton2.setText("Tinh Vệ");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jRadioButton3.setText("Tinh Vũ");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jRadioButton4.setText("Tinh Vân");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jRadioButton5.setText("Tinh Võ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(null);

        img.setBackground(new java.awt.Color(251, 251, 251));
        jScrollPane2.setViewportView(img);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // Answer A selected
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    // ===== GAME LOGIC METHODS =====

    private void setupQuestionUI() {
        setTitle(question.getTitle());
        jRadioButton2.setText(question.getA());
        jRadioButton3.setText(question.getB());
        jRadioButton4.setText(question.getC());
        jRadioButton5.setText(question.getD());
        buttonGroup1.clearSelection();
    }

    private void startNextQuestion() {
        if (currentQuestionIndex >= songs.size()) {
            finishGame();
            return;
        }

        Music currentSong = songs.get(currentQuestionIndex);
        setTitle("Q" + (currentQuestionIndex + 1) + "/" + songs.size() + " | Score: " + myScore);

        buttonGroup1.clearSelection();
        disableAnswers();

        // Show image
        img.setContentType("text/html");
        img.setText("<html><img src='" + currentSong.getImage() + "' width='200'></html>");
        img.setEditable(false);
        img.setOpaque(false);
        img.setBorder(null);
        img.setHighlighter(null);
        img.setCaret(null);

        // Phase 1: Play 5s preview
        playAudioSegment(currentSong.getFileName(), 5, () -> {
            // Phase 2: 10s answer time
            enableAnswers();
            startCountdown(10, () -> {
                // Phase 3: Check answer and play 20s result
                disableAnswers();
                checkAnswer();
                String resultFile = currentSong.getFileName().replace(".wav", "-result.wav");
                playAudioSegment(resultFile, 20, () -> {
                    currentQuestionIndex++;
                    startNextQuestion();
                });
            });
        });
    }

    private void playAudioSegment(String songFile, int seconds, Runnable onComplete) {
        MessageRequest request = new MessageRequest();
        request.setType("getSegment");
        request.setContent("{\"songFile\":\"" + songFile + "\",\"segmentSeconds\":" + seconds + "}");
        String reqId = UUID.randomUUID().toString();
        request.setId(reqId);

        MessageRouter.getInstance().registerRequestHandler(reqId, response -> {
            SwingUtilities.invokeLater(() -> {
                if (MessageResponse.SUCCESS.equals(response.getStatus())) {
                    String base64Data = response.getMessage();
                    byte[] audioBytes = Base64.getDecoder().decode(base64Data);

                    try (ByteArrayInputStream bais = new ByteArrayInputStream(audioBytes);
                         AudioInputStream audioStream = AudioSystem.getAudioInputStream(bais)) {

                        stopCurrentAudio();
                        currentClip = AudioSystem.getClip();
                        currentClip.open(audioStream);
                        currentClip.start();

                        gameTimer.schedule(new TimerTask() {
                            @Override
                            public void run() {
                                SwingUtilities.invokeLater(() -> {
                                    if (onComplete != null) onComplete.run();
                                });
                            }
                        }, seconds * 1000);

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
                MessageRouter.getInstance().unregisterRequestHandler(reqId);
            });
        });

        clientNetwork.sendMessage(request);
    }

    private void startCountdown(int seconds, Runnable onComplete) {
        final int[] remaining = {seconds};

        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                SwingUtilities.invokeLater(() -> {
                    remaining[0]--;
                    setTitle("Q" + (currentQuestionIndex + 1) + "/" + songs.size() +
                            " | Time: " + remaining[0] + "s | Score: " + myScore);

                    if (remaining[0] <= 0) {
                        this.cancel();
                        if (onComplete != null) onComplete.run();
                    }
                });
            }
        };

        gameTimer.scheduleAtFixedRate(task, 1000, 1000);
    }

    private void checkAnswer() {
        String selected = getSelectedAnswer();
        if (selected != null && selected.equals(question.getAnswer())) {
            myScore++;
            setTitle("Q" + (currentQuestionIndex + 1) + "/" + songs.size() + " | CORRECT! Score: " + myScore);
        } else {
            setTitle("Q" + (currentQuestionIndex + 1) + "/" + songs.size() + " | Wrong. Score: " + myScore);
        }
    }

    private String getSelectedAnswer() {
        if (jRadioButton2.isSelected()) return "A";
        if (jRadioButton3.isSelected()) return "B";
        if (jRadioButton4.isSelected()) return "C";
        if (jRadioButton5.isSelected()) return "D";
        return null;
    }

    private void enableAnswers() {
        jRadioButton2.setEnabled(true);
        jRadioButton3.setEnabled(true);
        jRadioButton4.setEnabled(true);
        jRadioButton5.setEnabled(true);
    }

    private void disableAnswers() {
        jRadioButton2.setEnabled(false);
        jRadioButton3.setEnabled(false);
        jRadioButton4.setEnabled(false);
        jRadioButton5.setEnabled(false);
    }

    private void stopCurrentAudio() {
        if (currentClip != null && currentClip.isRunning()) {
            currentClip.stop();
            currentClip.close();
        }
    }

    private void finishGame() {
        stopCurrentAudio();
        if (gameTimer != null) gameTimer.cancel();

        // Chỉ gọi submitScore, nó sẽ tự gọi sendLeaveRoom sau khi hoàn tất
        submitScore();

        JOptionPane.showMessageDialog(this,
                "Game finished! Your score: " + myScore + "/" + songs.size() +
                "\n\nWaiting for other players...",
                "Game Over", JOptionPane.INFORMATION_MESSAGE);
    }

    private void submitScore() {
        try {
            JsonObject data = new JsonObject();
            data.addProperty("roomId", roomId);
            data.addProperty("score", myScore);

            MessageRequest request = new MessageRequest();
            request.setType("submit_score");
            request.setContent(data.toString());
            request.setUsername(ClientConnection.getInstance().getUsername());
            String reqId = UUID.randomUUID().toString();
            request.setId(reqId);

            MessageRouter.getInstance().registerRequestHandler(reqId, response -> {
                System.out.println("Score submitted: " + response.getMessage());

                // Sau khi submit score thành công, mới gửi leave room
                // Đảm bảo điểm đã được lưu vào database trước khi trigger final calculation
                sendLeaveRoom();

                MessageRouter.getInstance().unregisterRequestHandler(reqId);
            });

            clientNetwork.sendMessage(request);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void sendLeaveRoom() {
        try {
            MessageRequest request = new MessageRequest();
            request.setType("leave_room");
            request.setContent(String.valueOf(roomId));
            request.setUsername(ClientConnection.getInstance().getUsername());
            String reqId = UUID.randomUUID().toString();
            request.setId(reqId);

            clientNetwork.sendMessage(request);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void handleFinalScores(String message) {
        try {
            JsonObject data = new Gson().fromJson(message, JsonObject.class);
            String winner = data.get("winner").getAsString();
            JsonObject scores = data.getAsJsonObject("finalScores");

            StringBuilder result = new StringBuilder("=== FINAL SCORES ===\n\n");
            scores.entrySet().forEach(entry -> {
                result.append(entry.getKey()).append(": ").append(entry.getValue()).append(" points\n");
            });
            result.append("\nWinner: ").append(winner).append("!");

            JOptionPane.showMessageDialog(this, result.toString(), "Game Results", JOptionPane.INFORMATION_MESSAGE);

            this.dispose();
            new HomeFrm(ClientConnection.getInstance().getUsername()).setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayGameFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayGameFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayGameFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayGameFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PlayGameFrm().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JEditorPane img;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
